### ISSUE TITLE
Compatibility with WPML plugin

### ISSUE THREAD

**Issue by AmeliaBriscoe** [Prospress/woocommerce-subscriptions-custom-price-string#4]
A customer wished to change the text on the checkout page where recommending the custom price string mini-plugin was appropriate.

The customer advised that it solved the problem, but added that:

> It would be even greater if the plugin works with the WPML plugin for multilangual websites

Adding the suggestion here as an enhancement request

**Comment by bernattorras** [comment]
I think that you can set this custom field as translatable in WPML>Settings>Custom Fields Translation page. You just need to click the "show system fields" link and set the "_custom_price_string" field as translatable. 

Once done, it should appear as a translatable field in their translation GUI. 

In any case, we should add a `wpml-config.xml` field to the plugin to specify the custom fields that WPML should automatically consider as translatable (`custom_price_string` and `custom_from_string`).
